SortOrder:
 - COAL_ORE
 - DIAMOND_ORE
 - EMERALD_ORE
 - GOLD_ORE
 - IRON_ORE
 - LAPIS_ORE
 - NETHER_QUARTZ_ORE
 - REDSTONE_ORE
 - STONE
 - SMOOTH_STONE
 - STONE_BRICKS
 - CRACKED_STONE_BRICKS
 - CHISELED_STONE_BRICKS
 - MOSSY_STONE_BRICKS
 - COBBLESTONE
 - MOSSY_COBBLESTONE
 - DIORITE
 - POLISHED_DIORITE
 - GRANITE
 - POLISHED_GRANITE
 - ANDESITE
 - POLISHED_ANDESITE
 - SANDSTONE
 - SMOOTH_SANDSTONE
 - CHISELED_SANDSTONE
 - CUT_SANDSTONE
 - RED_SANDSTONE
 - SMOOTH_RED_SANDSTONE
 - CHISELED_RED_SANDSTONE
 - CUT_RED_SANDSTONE
 - BRICKS
 - OBSIDIAN
 - PRISMARINE
 - PRISMARINE_BRICKS
 - DARK_PRISMARINE
 - NETHERRACK
 - NETHER_BRICKS
 - RED_NETHER_BRICKS
 - QUARTZ_BLOCK
 - QUARTZ_PILLAR
 - SMOOTH_QUARTZ
 - CHISELED_QUARTZ_BLOCK
 - END_STONE
 - END_STONE_BRICKS
 - PURPUR_BLOCK
 - PURPUR_PILLAR
 - PURPUR_STAIRS
 - GRASS_BLOCK
 - GRASS_PATH
 - DIRT
 - COARSE_DIRT
 - PODZOL
 - MYCELIUM
 - SAND
 - RED_SAND
 - GRAVEL
 - CLAY
 - SOUL_SAND
 - SLIME_BLOCK
 - BONE_BLOCK
 - RED_MUSHROOM_BLOCK
 - BROWN_MUSHROOM_BLOCK
 - COAL_BLOCK
 - IRON_BLOCK
 - GOLD_BLOCK
 - LAPIS_BLOCK
 - EMERALD_BLOCK
 - DIAMOND_BLOCK
 - MAGMA_BLOCK
 - NETHER_WART_BLOCK
 - OAK_PLANKS
 - SPRUCE_PLANKS
 - BIRCH_PLANKS
 - JUNGLE_PLANKS
 - ACACIA_PLANKS
 - DARK_OAK_PLANKS
 - OAK_LOG
 - SPRUCE_LOG
 - BIRCH_LOG
 - JUNGLE_LOG
 - ACACIA_LOG
 - DARK_OAK_LOG
 - STRIPPED_OAK_LOG
 - STRIPPED_SPRUCE_LOG
 - STRIPPED_BIRCH_LOG
 - STRIPPED_JUNGLE_LOG
 - STRIPPED_ACACIA_LOG
 - STRIPPED_DARK_OAK_LOG
 - OAK_WOOD
 - SPRUCE_WOOD
 - BIRCH_WOOD
 - JUNGLE_WOOD
 - ACACIA_WOOD
 - DARK_OAK_WOOD
 - STRIPPED_OAK_WOOD
 - STRIPPED_SPRUCE_WOOD
 - STRIPPED_BIRCH_WOOD
 - STRIPPED_JUNGLE_WOOD
 - STRIPPED_ACACIA_WOOD
 - STRIPPED_DARK_OAK_WOOD
 - MUSHROOM_STEM
 - TERRACOTTA
 - WHITE_TERRACOTTA
 - ORANGE_TERRACOTTA
 - MAGENTA_TERRACOTTA
 - LIGHT_BLUE_TERRACOTTA
 - YELLOW_TERRACOTTA
 - LIME_TERRACOTTA
 - PINK_TERRACOTTA
 - GRAY_TERRACOTTA
 - LIGHT_GRAY_TERRACOTTA
 - CYAN_TERRACOTTA
 - PURPLE_TERRACOTTA
 - BLUE_TERRACOTTA
 - BROWN_TERRACOTTA
 - GREEN_TERRACOTTA
 - RED_TERRACOTTA
 - BLACK_TERRACOTTA
 - WHITE_GLAZED_TERRACOTTA
 - ORANGE_GLAZED_TERRACOTTA
 - MAGENTA_GLAZED_TERRACOTTA
 - LIGHT_BLUE_GLAZED_TERRACOTTA
 - YELLOW_GLAZED_TERRACOTTA
 - LIME_GLAZED_TERRACOTTA
 - PINK_GLAZED_TERRACOTTA
 - GRAY_GLAZED_TERRACOTTA
 - LIGHT_GRAY_GLAZED_TERRACOTTA
 - CYAN_GLAZED_TERRACOTTA
 - PURPLE_GLAZED_TERRACOTTA
 - BLUE_GLAZED_TERRACOTTA
 - BROWN_GLAZED_TERRACOTTA
 - GREEN_GLAZED_TERRACOTTA
 - RED_GLAZED_TERRACOTTA
 - BLACK_GLAZED_TERRACOTTA
 - WHITE_CONCRETE_POWDER
 - ORANGE_CONCRETE_POWDER
 - MAGENTA_CONCRETE_POWDER
 - LIGHT_BLUE_CONCRETE_POWDER
 - YELLOW_CONCRETE_POWDER
 - LIME_CONCRETE_POWDER
 - PINK_CONCRETE_POWDER
 - GRAY_CONCRETE_POWDER
 - LIGHT_GRAY_CONCRETE_POWDER
 - CYAN_CONCRETE_POWDER
 - PURPLE_CONCRETE_POWDER
 - BLUE_CONCRETE_POWDER
 - BROWN_CONCRETE_POWDER
 - GREEN_CONCRETE_POWDER
 - RED_CONCRETE_POWDER
 - BLACK_CONCRETE_POWDER
 - WHITE_CONCRETE
 - ORANGE_CONCRETE
 - MAGENTA_CONCRETE
 - LIGHT_BLUE_CONCRETE
 - YELLOW_CONCRETE
 - LIME_CONCRETE
 - PINK_CONCRETE
 - GRAY_CONCRETE
 - LIGHT_GRAY_CONCRETE
 - CYAN_CONCRETE
 - PURPLE_CONCRETE
 - BLUE_CONCRETE
 - BROWN_CONCRETE
 - GREEN_CONCRETE
 - RED_CONCRETE
 - BLACK_CONCRETE
 - GLASS
 - BLACK_STAINED_GLASS
 - BLUE_STAINED_GLASS
 - BROWN_STAINED_GLASS
 - CYAN_STAINED_GLASS
 - GRAY_STAINED_GLASS
 - GREEN_STAINED_GLASS
 - LIGHT_BLUE_STAINED_GLASS
 - LIGHT_GRAY_STAINED_GLASS
 - LIME_STAINED_GLASS
 - MAGENTA_STAINED_GLASS
 - ORANGE_STAINED_GLASS
 - PINK_STAINED_GLASS
 - PURPLE_STAINED_GLASS
 - RED_STAINED_GLASS
 - WHITE_STAINED_GLASS
 - YELLOW_STAINED_GLASS
 - WHITE_STAINED_GLASS_PANE
 - ORANGE_STAINED_GLASS_PANE
 - MAGENTA_STAINED_GLASS_PANE
 - LIGHT_BLUE_STAINED_GLASS_PANE
 - YELLOW_STAINED_GLASS_PANE
 - LIME_STAINED_GLASS_PANE
 - PINK_STAINED_GLASS_PANE
 - GRAY_STAINED_GLASS_PANE
 - LIGHT_GRAY_STAINED_GLASS_PANE
 - CYAN_STAINED_GLASS_PANE
 - PURPLE_STAINED_GLASS_PANE
 - BLUE_STAINED_GLASS_PANE
 - BROWN_STAINED_GLASS_PANE
 - GREEN_STAINED_GLASS_PANE
 - RED_STAINED_GLASS_PANE
 - BLACK_STAINED_GLASS_PANE
 - BLACK_WOOL
 - BLUE_WOOL
 - BROWN_WOOL
 - CYAN_WOOL
 - GRAY_WOOL
 - GREEN_WOOL
 - LIGHT_BLUE_WOOL
 - LIGHT_GRAY_WOOL
 - LIME_WOOL
 - MAGENTA_WOOL
 - ORANGE_WOOL
 - PINK_WOOL
 - PURPLE_WOOL
 - RED_WOOL
 - WHITE_WOOL
 - YELLOW_WOOL
 - WHITE_CARPET
 - ORANGE_CARPET
 - MAGENTA_CARPET
 - LIGHT_BLUE_CARPET
 - YELLOW_CARPET
 - LIME_CARPET
 - PINK_CARPET
 - GRAY_CARPET
 - LIGHT_GRAY_CARPET
 - CYAN_CARPET
 - PURPLE_CARPET
 - BLUE_CARPET
 - BROWN_CARPET
 - GREEN_CARPET
 - RED_CARPET
 - BLACK_CARPET
 - BLACK_BANNER
 - BLUE_BANNER
 - BROWN_BANNER
 - CYAN_BANNER
 - GRAY_BANNER
 - GREEN_BANNER
 - LIGHT_BLUE_BANNER
 - LIGHT_GRAY_BANNER
 - LIME_BANNER
 - MAGENTA_BANNER
 - ORANGE_BANNER
 - PINK_BANNER
 - PURPLE_BANNER
 - RED_BANNER
 - WHITE_BANNER
 - YELLOW_BANNER
 - STONE_SLAB
 - STONE_BRICK_SLAB
 - COBBLESTONE_SLAB
 - SANDSTONE_SLAB
 - RED_SANDSTONE_SLAB
 - BRICK_SLAB
 - PRISMARINE_SLAB
 - PRISMARINE_BRICK_SLAB
 - DARK_PRISMARINE_SLAB
 - NETHER_BRICK_SLAB
 - QUARTZ_SLAB
 - PURPUR_SLAB
 - OAK_SLAB
 - PETRIFIED_OAK_SLAB
 - SPRUCE_SLAB
 - BIRCH_SLAB
 - JUNGLE_SLAB
 - ACACIA_SLAB
 - DARK_OAK_SLAB
 - STONE_BRICK_STAIRS
 - COBBLESTONE_STAIRS
 - SANDSTONE_STAIRS
 - RED_SANDSTONE_STAIRS
 - BRICK_STAIRS
 - PRISMARINE_STAIRS
 - PRISMARINE_BRICK_STAIRS
 - DARK_PRISMARINE_STAIRS
 - NETHER_BRICK_STAIRS
 - QUARTZ_STAIRS
 - PURPUR_STAIRS
 - OAK_STAIRS
 - SPRUCE_STAIRS
 - BIRCH_STAIRS
 - JUNGLE_STAIRS
 - ACACIA_STAIRS
 - DARK_OAK_STAIRS
 - IRON_BARS
 - COBBLESTONE_WALL
 - MOSSY_COBBLESTONE_WALL
 - NETHER_BRICK_FENCE
 - OAK_FENCE
 - SPRUCE_FENCE
 - BIRCH_FENCE
 - JUNGLE_FENCE
 - ACACIA_FENCE
 - DARK_OAK_FENCE
 - PUMPKIN
 - CARVED_PUMPKIN
 - HAY_BLOCK
 - ICE
 - PACKED_ICE
 - BLUE_ICE
 - SPONGE
 - WET_SPONGE
 - SEA_LANTERN
 - SNOW_BLOCK
 - TUBE_CORAL_BLOCK
 - BRAIN_CORAL_BLOCK
 - BUBBLE_CORAL_BLOCK
 - FIRE_CORAL_BLOCK
 - HORN_CORAL_BLOCK
 - DEAD_TUBE_CORAL_BLOCK
 - DEAD_BRAIN_CORAL_BLOCK
 - DEAD_BUBBLE_CORAL_BLOCK
 - DEAD_FIRE_CORAL_BLOCK
 - DEAD_HORN_CORAL_BLOCK
 - TUBE_CORAL
 - TUBE_CORAL_FAN
 - DEAD_TUBE_CORAL_FAN
 - BRAIN_CORAL
 - BRAIN_CORAL_FAN
 - DEAD_BRAIN_CORAL_FAN
 - BUBBLE_CORAL
 - BUBBLE_CORAL_FAN
 - DEAD_BUBBLE_CORAL_FAN
 - FIRE_CORAL
 - FIRE_CORAL_FAN
 - DEAD_FIRE_CORAL_FAN
 - HORN_CORAL
 - HORN_CORAL_FAN
 - DEAD_HORN_CORAL_FAN
 - DRIED_KELP_BLOCK
 - BOOKSHELF
 - OAK_SAPLING
 - SPRUCE_SAPLING
 - BIRCH_SAPLING
 - JUNGLE_SAPLING
 - ACACIA_SAPLING
 - DARK_OAK_SAPLING
 - OAK_LEAVES
 - SPRUCE_LEAVES
 - BIRCH_LEAVES
 - JUNGLE_LEAVES
 - ACACIA_LEAVES
 - DARK_OAK_LEAVES
 - STRING
 - COBWEB
 - GRASS
 - FERN
 - DEAD_BUSH
 - DANDELION
 - POPPY
 - BLUE_ORCHID
 - ALLIUM
 - AZURE_BLUET
 - RED_TULIP
 - ORANGE_TULIP
 - WHITE_TULIP
 - PINK_TULIP
 - OXEYE_DAISY
 - SUNFLOWER
 - LILAC
 - TALL_GRASS
 - LARGE_FERN
 - ROSE_BUSH
 - PEONY
 - BROWN_MUSHROOM
 - RED_MUSHROOM
 - CACTUS
 - VINE
 - LILY_PAD
 - CHORUS_FRUIT
 - CHORUS_PLANT
 - CHORUS_FLOWER
 - POPPED_CHORUS_FRUIT
 - SEAGRASS
 - SEA_PICKLE
 - KELP
 - BEETROOT_SEEDS
 - MELON_SEEDS
 - PUMPKIN_SEEDS
 - WHEAT_SEEDS
 - BEETROOT
 - CARROT
 - POTATO
 - SUGAR_CANE
 - WHEAT
 - BAKED_POTATO
 - POISONOUS_POTATO
 - ENCHANTED_GOLDEN_APPLE
 - APPLE
 - MELON_SLICE
 - MELON
 - COOKED_BEEF
 - COOKED_CHICKEN
 - COOKED_PORKCHOP
 - COOKED_RABBIT
 - COOKED_MUTTON
 - COOKED_COD
 - COOKED_SALMON
 - BEEF
 - ROTTEN_FLESH
 - CHICKEN
 - PORKCHOP
 - RABBIT
 - MUTTON
 - COD
 - SALMON
 - TROPICAL_FISH
 - PUFFERFISH
 - COD_BUCKET
 - NAUTILUS_SHELL
 - DRIED_KELP
 - BREAD
 - PUMPKIN_PIE
 - SUGAR
 - COOKIE
 - CAKE
 - RABBIT_STEW
 - MUSHROOM_STEW
 - BEETROOT_SOUP
 - SALMON_BUCKET
 - TROPICAL_FISH_BUCKET
 - PUFFERFISH_BUCKET
 - CRAFTING_TABLE
 - CHEST
 - ENDER_CHEST
 - SHULKER_BOX
 - WHITE_SHULKER_BOX
 - ORANGE_SHULKER_BOX
 - MAGENTA_SHULKER_BOX
 - LIGHT_BLUE_SHULKER_BOX
 - YELLOW_SHULKER_BOX
 - LIME_SHULKER_BOX
 - PINK_SHULKER_BOX
 - GRAY_SHULKER_BOX
 - LIGHT_GRAY_SHULKER_BOX
 - CYAN_SHULKER_BOX
 - PURPLE_SHULKER_BOX
 - BLUE_SHULKER_BOX
 - BROWN_SHULKER_BOX
 - GREEN_SHULKER_BOX
 - RED_SHULKER_BOX
 - BLACK_SHULKER_BOX
 - FURNACE
 - ANVIL
 - CHIPPED_ANVIL
 - DAMAGED_ANVIL
 - ENCHANTING_TABLE
 - BREWING_STAND
 - SIGN
 - PAINTING
 - ITEM_FRAME
 - ARMOR_STAND
 - FLOWER_POT
 - CAULDRON
 - WHITE_BED
 - ORANGE_BED
 - MAGENTA_BED
 - LIGHT_BLUE_BED
 - YELLOW_BED
 - LIME_BED
 - PINK_BED
 - GRAY_BED
 - LIGHT_GRAY_BED
 - CYAN_BED
 - PURPLE_BED
 - BLUE_BED
 - BROWN_BED
 - GREEN_BED
 - RED_BED
 - BLACK_BED
 - REDSTONE_BLOCK
 - REDSTONE_TORCH
 - LEVER
 - STONE_PRESSURE_PLATE
 - LIGHT_WEIGHTED_PRESSURE_PLATE
 - HEAVY_WEIGHTED_PRESSURE_PLATE
 - OAK_PRESSURE_PLATE
 - SPRUCE_PRESSURE_PLATE
 - BIRCH_PRESSURE_PLATE
 - JUNGLE_PRESSURE_PLATE
 - ACACIA_PRESSURE_PLATE
 - DARK_OAK_PRESSURE_PLATE
 - STONE_BUTTON
 - OAK_BUTTON
 - SPRUCE_BUTTON
 - BIRCH_BUTTON
 - JUNGLE_BUTTON
 - ACACIA_BUTTON
 - DARK_OAK_BUTTON
 - TRIPWIRE_HOOK
 - TRAPPED_CHEST
 - DAYLIGHT_DETECTOR
 - OBSERVER
 - COMPARATOR
 - REPEATER
 - REDSTONE
 - OAK_DOOR
 - SPRUCE_DOOR
 - BIRCH_DOOR
 - JUNGLE_DOOR
 - ACACIA_DOOR
 - DARK_OAK_DOOR
 - IRON_DOOR
 - OAK_TRAPDOOR
 - SPRUCE_TRAPDOOR
 - BIRCH_TRAPDOOR
 - JUNGLE_TRAPDOOR
 - ACACIA_TRAPDOOR
 - DARK_OAK_TRAPDOOR
 - IRON_TRAPDOOR
 - OAK_FENCE_GATE
 - SPRUCE_FENCE_GATE
 - BIRCH_FENCE_GATE
 - JUNGLE_FENCE_GATE
 - ACACIA_FENCE_GATE
 - DARK_OAK_FENCE_GATE
 - PISTON
 - STICKY_PISTON
 - DISPENSER
 - DROPPER
 - HOPPER
 - REDSTONE_LAMP
 - NOTE_BLOCK
 - JUKEBOX
 - TNT
 - POWERED_RAIL
 - DETECTOR_RAIL
 - RAIL
 - ACTIVATOR_RAIL
 - MINECART
 - CHEST_MINECART
 - FURNACE_MINECART
 - HOPPER_MINECART
 - TNT_MINECART
 - CARROT_ON_A_STICK
 - SADDLE
 - OAK_BOAT
 - SPRUCE_BOAT
 - BIRCH_BOAT
 - JUNGLE_BOAT
 - ACACIA_BOAT
 - DARK_OAK_BOAT
 - ELYTRA
 - LADDER
 - WOODEN_AXE
 - WOODEN_HOE
 - WOODEN_PICKAXE
 - WOODEN_SHOVEL
 - STONE_AXE
 - STONE_PICKAXE
 - STONE_SHOVEL
 - STONE_HOE
 - IRON_AXE
 - IRON_PICKAXE
 - IRON_SHOVEL
 - IRON_HOE
 - GOLDEN_AXE
 - GOLDEN_PICKAXE
 - GOLDEN_SHOVEL
 - GOLDEN_HOE
 - DIAMOND_AXE
 - DIAMOND_PICKAXE
 - DIAMOND_SHOVEL
 - DIAMOND_HOE
 - FLINT_AND_STEEL
 - COMPASS
 - FISHING_ROD
 - CLOCK
 - SHEARS
 - LEAD
 - NAME_TAG
 - ENCHANTED_BOOK
 - POTION
 - LINGERING_POTION
 - SPLASH_POTION
 - BOW
 - SPECTRAL_ARROW
 - TIPPED_ARROW
 - ARROW
 - WOODEN_SWORD
 - STONE_SWORD
 - LEATHER_HELMET
 - LEATHER_CHESTPLATE
 - LEATHER_LEGGINGS
 - LEATHER_BOOTS
 - TURTLE_HELMET
 - CHAINMAIL_HELMET
 - CHAINMAIL_CHESTPLATE
 - CHAINMAIL_LEGGINGS
 - CHAINMAIL_BOOTS
 - IRON_SWORD
 - IRON_HELMET
 - IRON_CHESTPLATE
 - IRON_LEGGINGS
 - IRON_BOOTS
 - GOLDEN_SWORD
 - GOLDEN_HELMET
 - GOLDEN_CHESTPLATE
 - GOLDEN_LEGGINGS
 - GOLDEN_BOOTS
 - DIAMOND_SWORD
 - DIAMOND_HELMET
 - DIAMOND_CHESTPLATE
 - DIAMOND_LEGGINGS
 - DIAMOND_BOOTS
 - TRIDENT
 - SHIELD
 - TOTEM_OF_UNDYING
 - IRON_HORSE_ARMOR
 - GOLDEN_HORSE_ARMOR
 - DIAMOND_HORSE_ARMOR
 - GLASS_BOTTLE
 - FLINT
 - CLAY_BALL
 - CHARCOAL
 - COAL
 - EMERALD
 - DIAMOND
 - TORCH
 - END_ROD
 - JACK_O_LANTERN
 - BONE
 - GUNPOWDER
 - SLIME_BALL
 - NETHER_WART
 - GOLDEN_CARROT
 - GOLDEN_APPLE
 - GLISTERING_MELON_SLICE
 - FERMENTED_SPIDER_EYE
 - RABBIT_FOOT
 - SPIDER_EYE
 - PHANTOM_MEMBRANE
 - GHAST_TEAR
 - MAGMA_CREAM
 - BLAZE_POWDER
 - BLAZE_ROD
 - ENDER_EYE
 - ENDER_PEARL
 - EGG
 - TURTLE_EGG
 - SCUTE
 - FEATHER
 - LEATHER
 - RABBIT_HIDE
 - SNOWBALL
 - PRISMARINE_SHARD
 - PRISMARINE_CRYSTALS
 - QUARTZ
 - SHULKER_SHELL
 - STICK
 - BOWL
 - PAPER
 - FILLED_MAP
 - MAP
 - BOOK
 - WRITABLE_BOOK
 - WRITTEN_BOOK
 - KNOWLEDGE_BOOK
 - BUCKET
 - LAVA_BUCKET
 - WATER_BUCKET
 - MILK_BUCKET
 - NETHER_BRICK
 - IRON_INGOT
 - GOLD_INGOT
 - IRON_NUGGET
 - GOLD_NUGGET
 - FIRE_CHARGE
 - FIREWORK_ROCKET
 - FIREWORK_STAR
 - BONE_MEAL
 - ORANGE_DYE
 - MAGENTA_DYE
 - LIGHT_BLUE_DYE
 - DANDELION_YELLOW
 - LIME_DYE
 - PINK_DYE
 - GRAY_DYE
 - LIGHT_GRAY_DYE
 - CYAN_DYE
 - PURPLE_DYE
 - LAPIS_LAZULI
 - COCOA_BEANS
 - CACTUS_GREEN
 - ROSE_RED
 - INK_SAC
 - NETHER_STAR
 - HEART_OF_THE_SEA
 - BEACON
 - CONDUIT
 - DRAGON_BREATH
 - CREEPER_HEAD
 - DRAGON_HEAD
 - PLAYER_HEAD
 - ZOMBIE_HEAD
 - SKELETON_SKULL
 - WITHER_SKELETON_SKULL
 - END_CRYSTAL
 - DRAGON_EGG
 - MUSIC_DISC_11
 - MUSIC_DISC_13
 - MUSIC_DISC_BLOCKS
 - MUSIC_DISC_CAT
 - MUSIC_DISC_CHIRP
 - MUSIC_DISC_FAR
 - MUSIC_DISC_MALL
 - MUSIC_DISC_MELLOHI
 - MUSIC_DISC_STAL
 - MUSIC_DISC_STRAD
 - MUSIC_DISC_WAIT
 - MUSIC_DISC_WARD
 - BAT_SPAWN_EGG
 - BLAZE_SPAWN_EGG
 - CAVE_SPIDER_SPAWN_EGG
 - CHICKEN_SPAWN_EGG
 - COD_SPAWN_EGG
 - COW_SPAWN_EGG
 - CREEPER_SPAWN_EGG
 - DOLPHIN_SPAWN_EGG
 - DONKEY_SPAWN_EGG
 - DROWNED_SPAWN_EGG
 - ELDER_GUARDIAN_SPAWN_EGG
 - ENDERMAN_SPAWN_EGG
 - ENDERMITE_SPAWN_EGG
 - EVOKER_SPAWN_EGG
 - GHAST_SPAWN_EGG
 - GUARDIAN_SPAWN_EGG
 - HORSE_SPAWN_EGG
 - HUSK_SPAWN_EGG
 - LLAMA_SPAWN_EGG
 - MAGMA_CUBE_SPAWN_EGG
 - MOOSHROOM_SPAWN_EGG
 - MULE_SPAWN_EGG
 - OCELOT_SPAWN_EGG
 - PARROT_SPAWN_EGG
 - PHANTOM_SPAWN_EGG
 - PIG_SPAWN_EGG
 - POLAR_BEAR_SPAWN_EGG
 - PUFFERFISH_SPAWN_EGG
 - RABBIT_SPAWN_EGG
 - SALMON_SPAWN_EGG
 - SHEEP_SPAWN_EGG
 - SHULKER_SPAWN_EGG
 - SILVERFISH_SPAWN_EGG
 - SKELETON_HORSE_SPAWN_EGG
 - SKELETON_SPAWN_EGG
 - SLIME_SPAWN_EGG
 - SPIDER_SPAWN_EGG
 - SQUID_SPAWN_EGG
 - STRAY_SPAWN_EGG
 - TROPICAL_FISH_SPAWN_EGG
 - TURTLE_SPAWN_EGG
 - VEX_SPAWN_EGG
 - VILLAGER_SPAWN_EGG
 - VINDICATOR_SPAWN_EGG
 - WITCH_SPAWN_EGG
 - WITHER_SKELETON_SPAWN_EGG
 - WOLF_SPAWN_EGG
 - ZOMBIE_HORSE_SPAWN_EGG
 - ZOMBIE_PIGMAN_SPAWN_EGG
 - ZOMBIE_SPAWN_EGG
 - ZOMBIE_VILLAGER_SPAWN_EGG
 - STRUCTURE_BLOCK
 - STRUCTURE_VOID